import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, Send } from 'lucide-react';
import { supabase } from '../supabaseClient';

const statuses = ['open', 'in_progress', 'resolved', 'closed'];

export default function AdminPriorityTickets() {
  const [tickets, setTickets] = useState([]);
  const [selected, setSelected] = useState(null);
  const [thread, setThread] = useState([]);
  const [reply, setReply] = useState('');
  const [status, setStatus] = useState('all');
  const [tier, setTier] = useState('all');

  async function load() { const { data } = await supabase.from('support_tickets').select('*').order('created_at', { ascending: false }); setTickets((data || []).sort((a, b) => Number(b.tier === 'premium') - Number(a.tier === 'premium'))); }
  useEffect(() => { load(); }, []);
  useEffect(() => { const channel = supabase.channel('admin-support-tickets-live').on('postgres_changes', { event: '*', schema: 'public', table: 'support_tickets' }, (payload) => { setTickets((items) => payload.eventType === 'INSERT' ? [payload.new, ...items] : items.map((item) => item.id === payload.new.id ? { ...item, ...payload.new } : item)); if (selected?.id === payload.new?.id) setSelected((item) => ({ ...item, ...payload.new })); }).subscribe(); return () => supabase.removeChannel(channel); }, [selected?.id]);
  useEffect(() => { if (!selected) return undefined; const channel = supabase.channel(`admin-ticket-thread-${selected.id}`).on('postgres_changes', { event: 'INSERT', schema: 'public', table: 'support_ticket_messages', filter: `ticket_id=eq.${selected.id}` }, (payload) => setThread((items) => items.some((item) => item.id === payload.new.id) ? items : [...items, payload.new])).subscribe(); return () => supabase.removeChannel(channel); }, [selected?.id]);
  const filtered = useMemo(() => tickets.filter((ticket) => (status === 'all' || ticket.status === status) && (tier === 'all' || ticket.tier === tier)), [tickets, status, tier]);
  async function openTicket(ticket) { setSelected(ticket); const { data } = await supabase.from('support_ticket_messages').select('*').eq('ticket_id', ticket.id).order('created_at', { ascending: true }); setThread(data || []); }
  async function updateStatus(next) { await supabase.from('support_tickets').update({ status: next, updated_at: new Date().toISOString() }).eq('id', selected.id); setSelected((item) => ({ ...item, status: next })); setTickets((items) => items.map((item) => item.id === selected.id ? { ...item, status: next } : item)); }
  async function sendReply(event) { event.preventDefault(); if (!reply.trim()) return; const { data } = await supabase.from('support_ticket_messages').insert([{ ticket_id: selected.id, sender_id: (await supabase.auth.getUser()).data.user?.id, sender_role: 'admin', message: reply.trim() }]).select().single(); if (data) setThread((items) => [...items, data]); setReply(''); }

  if (selected) return <div className="p-5"><button onClick={() => setSelected(null)} className="mb-4 inline-flex items-center gap-2 text-sm font-bold text-purple-600"><ArrowLeft className="h-4 w-4" /> Back to tickets</button><div className="rounded-2xl border border-slate-200 dark:border-slate-800"><div className="flex flex-wrap items-start justify-between gap-3 border-b p-4 dark:border-slate-800"><div className="min-w-0"><div className="flex items-center gap-2">{selected.tier === 'premium' && <span className="rounded-full bg-purple-600 px-2 py-1 text-[9px] font-black text-white">PRIORITY TICKET</span>}<span className="text-xs text-slate-400">{selected.category}</span></div><h2 className="mt-2 text-lg font-black">{selected.subject}</h2><p className="text-sm text-slate-500">{selected.description || selected.message}</p>{selected.attachment_url && <img src={selected.attachment_url} alt="Ticket attachment" className="mt-3 max-h-56 max-w-full rounded-xl border object-contain" />}</div><select value={selected.status} onChange={(event) => updateStatus(event.target.value)} className="rounded-xl border px-3 py-2 text-xs font-bold dark:bg-slate-800">{statuses.map((item) => <option key={item}>{item}</option>)}</select></div><div className="max-h-[50vh] space-y-3 overflow-y-auto bg-slate-50 p-4 dark:bg-slate-950/30">{thread.map((item) => <div key={item.id} className={`flex ${item.sender_role === 'admin' ? 'justify-end' : 'justify-start'}`}><div className="max-w-[80%] rounded-2xl bg-white px-4 py-3 text-sm shadow-sm dark:bg-slate-800"><p>{item.message}</p>{item.attachment_url && <a href={item.attachment_url} target="_blank" rel="noreferrer"><img src={item.attachment_url} alt="Ticket attachment" className="mt-2 max-h-56 rounded-xl object-contain" /></a>}<span className="mt-1 block text-[9px] text-slate-400">{item.sender_role}</span></div></div>)}</div><form onSubmit={sendReply} className="flex gap-2 border-t p-3 dark:border-slate-800"><input value={reply} onChange={(event) => setReply(event.target.value)} placeholder="Reply to user..." className="min-w-0 flex-1 rounded-full bg-slate-100 px-4 py-2.5 text-sm outline-none dark:bg-slate-800" /><button className="rounded-full bg-purple-600 p-3 text-white"><Send className="h-4 w-4" /></button></form></div></div>;
  return <div className="p-5"><div className="flex flex-wrap items-center justify-between gap-3 border-b p-4"><h2 className="text-lg font-black">Support Tickets</h2><div className="flex gap-2"><select value={tier} onChange={(event) => setTier(event.target.value)} className="rounded-xl border px-3 py-2 text-xs"><option value="all">All tiers</option><option value="premium">Premium</option><option value="free">Free</option></select><select value={status} onChange={(event) => setStatus(event.target.value)} className="rounded-xl border px-3 py-2 text-xs"><option value="all">All statuses</option>{statuses.map((item) => <option key={item}>{item}</option>)}</select></div></div><div className="divide-y">{filtered.map((ticket) => <button key={ticket.id} onClick={() => openTicket(ticket)} className="flex w-full items-center justify-between gap-3 p-4 text-left hover:bg-purple-50/40"><div className="min-w-0"><div className="flex items-center gap-2">{ticket.tier === 'premium' && <span className="rounded-full bg-purple-600 px-2 py-1 text-[9px] font-black text-white">PRIORITY TICKET</span>}<span className="text-[10px] text-slate-400">{ticket.status}</span></div><p className="mt-1 truncate text-sm font-bold">{ticket.subject}</p><p className="truncate text-xs text-slate-500">{ticket.description || ticket.message}</p>{ticket.attachment_url && <span className="text-[10px] font-bold text-purple-600">Screenshot attached</span>}</div><span className="shrink-0 text-[10px] text-slate-400">{new Date(ticket.created_at).toLocaleDateString()}</span></button>)}</div>{!filtered.length && <p className="py-12 text-center text-sm text-slate-400">No matching support tickets.</p>}</div>;
}
