import { useEffect, useState } from 'react';
import { CheckCircle2, Search, ShieldCheck, XCircle } from 'lucide-react';
import { supabase } from '../supabaseClient';

export default function AdminPayments() {
  const [rows, setRows] = useState([]); const [profiles, setProfiles] = useState({}); const [query, setQuery] = useState(''); const [loading, setLoading] = useState(true); const [message, setMessage] = useState('');
  async function load() { setLoading(true); const { data, error } = await supabase.from('payments').select('id,user_id,email,txnid,payu_mihpayid,amount,status,created_at').order('created_at', { ascending: false }).limit(200); if (error) setMessage(error.message); setRows(data || []); const ids = [...new Set((data || []).map((row) => row.user_id).filter(Boolean))]; if (ids.length) { const { data: profileRows } = await supabase.from('profiles').select('id,is_verified,verified_until,subscription_plan').in('id', ids); setProfiles(Object.fromEntries((profileRows || []).map((profile) => [profile.id, profile]))); } setLoading(false); }
  useEffect(() => { load(); }, []);
  async function activate(userId) { const started = new Date(); const end = new Date(started); end.setMonth(end.getMonth() + 1); const { error } = await supabase.from('profiles').update({ is_verified: true, verified_until: end.toISOString(), subscription_started_at: started.toISOString(), subscription_plan: 'monthly' }).eq('id', userId); setMessage(error ? error.message : 'Premium activated successfully.'); if (!error) setProfiles((items) => ({ ...items, [userId]: { ...items[userId], is_verified: true, verified_until: end.toISOString(), subscription_plan: 'monthly' } })); }
  const needle = query.trim().toLowerCase(); const filtered = rows.filter((row) => !needle || row.user_id?.toLowerCase().includes(needle) || row.email?.toLowerCase().includes(needle) || row.txnid?.toLowerCase().includes(needle));
  return <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-black">Payment Audit</h2><p className="text-xs text-slate-500">Review payments and current Premium status.</p></div><button onClick={load} className="rounded-xl bg-purple-100 px-3 py-2 text-xs font-bold text-purple-700">Refresh</button></div><div className="relative mt-4"><Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-400" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search user ID, email or transaction ID" className="w-full rounded-xl border bg-slate-50 py-2.5 pl-9 pr-3 text-sm outline-none dark:border-slate-700 dark:bg-slate-800" /></div>{message && <p className="mt-3 rounded-xl bg-blue-50 p-3 text-xs text-blue-700">{message}</p>}<div className="mt-4 overflow-x-auto"><table className="w-full min-w-[850px] text-left text-xs"><thead><tr className="border-b text-slate-400"><th className="p-3">Status</th><th className="p-3">User / Email</th><th className="p-3">Txn ID</th><th className="p-3">Amount</th><th className="p-3">Premium now</th><th className="p-3">Action</th></tr></thead><tbody>{!loading && filtered.map((row) => { const profile = profiles[row.user_id]; return <tr key={row.id} className="border-b last:border-0 dark:border-slate-800"><td className="p-3">{row.status === 'success' ? <span className="inline-flex items-center gap-1 font-bold text-emerald-600"><CheckCircle2 className="h-4 w-4" />Success</span> : <span className="inline-flex items-center gap-1 font-bold text-rose-600"><XCircle className="h-4 w-4" />Failed</span>}</td><td className="p-3"><span className="block font-mono">{row.user_id}</span><span className="text-slate-500">{row.email || '—'}</span></td><td className="p-3 font-mono">{row.txnid || '—'}</td><td className="p-3">₹{row.amount}</td><td className="p-3">{profile?.is_verified ? <span className="font-bold text-emerald-600">Active</span> : <span className="text-slate-400">Inactive</span>}</td><td className="p-3"><button onClick={() => activate(row.user_id)} className="inline-flex items-center gap-1 rounded-lg bg-purple-600 px-2.5 py-2 font-bold text-white"><ShieldCheck className="h-3.5 w-3.5" />Activate</button></td></tr>; })}</tbody></table>{loading && <p className="p-8 text-center text-sm text-slate-400">Loading payments...</p>}{!loading && !filtered.length && <p className="p-8 text-center text-sm text-slate-400">No payments found.</p>}</div></section>;
}
