import { useEffect, useMemo, useState } from 'react';
import { ShieldCheck, RefreshCw, AlertCircle, CheckCircle2, Users, MessageSquare, FileText, Search, Trash2, XCircle } from 'lucide-react';
import { supabase } from '../supabaseClient';

const tabs = [['reports','Reports',AlertCircle],['users','Users',Users],['feedback','Feedback',MessageSquare],['deletions','Deletions',FileText]];
export default function Admin({ session }) {
  const [tab,setTab]=useState('reports'),[admin,setAdmin]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[reports,setReports]=useState([]),[users,setUsers]=useState([]),[feedback,setFeedback]=useState([]),[deletions,setDeletions]=useState([]),[query,setQuery]=useState('');
  const load=async()=>{setLoading(true);setError('');const [r,u,f,d]=await Promise.all([supabase.from('reports').select('*').order('created_at',{ascending:false}),supabase.from('profiles').select('id,username,full_name,avatar_url,account_status').order('created_at',{ascending:false}).limit(200),supabase.from('feedback').select('*').order('created_at',{ascending:false}),supabase.from('account_deletion_requests').select('*').order('requested_at',{ascending:false})]);if(r.error)setError(r.error.message);setReports(r.data||[]);setUsers(u.data||[]);setFeedback(f.data||[]);setDeletions(d.data||[]);setLoading(false);};
  useEffect(()=>{(async()=>{if(!session?.user?.id)return;const {data}=await supabase.from('admin_users').select('role').eq('user_id',session.user.id).maybeSingle();setAdmin(!!data&&['owner','admin','moderator'].includes(data.role));})();},[session?.user?.id]);
  useEffect(()=>{if(admin)load();},[admin]);
  const stats=useMemo(()=>({totalReports:reports.length,pending:reports.filter(x=>!x.status||x.status==='open'||x.status==='pending').length,resolved:reports.filter(x=>x.status==='resolved').length,deletions:deletions.length,pendingDeletions:deletions.filter(x=>(x.status||'pending')==='pending').length,totalUsers:users.length,active:users.filter(x=>x.account_status!=='suspended').length,suspended:users.filter(x=>x.account_status==='suspended').length,bugs:feedback.filter(x=>/bug/i.test(x.type||'')).length,features:feedback.filter(x=>/feature/i.test(x.type||'')).length,suggestions:feedback.filter(x=>/suggest/i.test(x.type||'')).length}),[reports,users,feedback,deletions]);
  async function reportAction(r,action){if(action==='delete'&&r.post_id){const {error:e}=await supabase.from('posts').delete().eq('id',r.post_id);if(e)return setError(e.message);}const {error:e}=await supabase.from('reports').update({status:action==='dismiss'?'dismissed':'resolved'}).eq('id',r.id);if(e)setError(e.message);else setReports(p=>p.map(x=>x.id===r.id?{...x,status:action==='dismiss'?'dismissed':'resolved'}:x));}
  async function toggleUser(u){const status=u.account_status==='suspended'?'active':'suspended';const {error:e}=await supabase.from('profiles').update({account_status:status}).eq('id',u.id);if(e)setError(e.message);else setUsers(p=>p.map(x=>x.id===u.id?{...x,account_status:status}:x));}
  async function deletionAction(d,status){const {error:e}=await supabase.from('account_deletion_requests').update({status}).eq('user_id',d.user_id);if(e)setError(e.message);else setDeletions(p=>p.map(x=>x.user_id===d.user_id?{...x,status}:x));}
  if(!admin)return <div className="min-h-screen grid place-items-center p-6 text-center"><AlertCircle className="text-rose-500 mb-3"/><h1 className="text-xl font-bold">Admin access required</h1></div>;
  const filteredUsers=users.filter(u=>`${u.full_name||''} ${u.username||''}`.toLowerCase().includes(query.toLowerCase()));
  const card=(label,value,sub,Icon,color)=><div className="rounded-2xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 p-4"><div className={`w-10 h-10 rounded-xl grid place-items-center ${color}`}><Icon className="w-5 h-5"/></div><p className="text-2xl font-black mt-3">{value}</p><p className="text-sm text-slate-600 dark:text-slate-300">{label}</p>{sub&&<p className="text-xs text-slate-400 mt-1">{sub}</p>}</div>;
  return <div className="min-h-screen bg-slate-50 dark:bg-slate-950 p-4 md:p-8"><div className="max-w-7xl mx-auto space-y-6"><header className="rounded-3xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 p-6 flex items-center justify-between"><div className="flex gap-4 items-center"><div className="p-4 rounded-2xl bg-gradient-to-br from-purple-600 to-fuchsia-500 text-white"><ShieldCheck/></div><div><h1 className="text-2xl md:text-3xl font-black">Admin Dashboard</h1><p className="text-sm text-slate-500">Manage reports, users, feedback and safety</p></div></div><button onClick={load} className="p-3 rounded-xl bg-purple-100 dark:bg-purple-950 text-purple-600"><RefreshCw className={loading?'animate-spin':''}/></button></header>
  <nav className="flex gap-2 overflow-x-auto rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 p-2">{tabs.map(([id,label,Icon])=><button key={id} onClick={()=>setTab(id)} className={`flex items-center gap-2 px-4 py-3 rounded-xl text-sm font-bold whitespace-nowrap ${tab===id?'bg-purple-600 text-white':'text-slate-600 dark:text-slate-300 hover:bg-slate-100 dark:hover:bg-slate-800'}`}><Icon className="w-4 h-4"/>{label}</button>)}</nav>
  <div className="grid grid-cols-2 md:grid-cols-4 gap-4">{tab==='reports'&&<>{card('Total Reports',stats.totalReports,`${stats.pending} pending`,AlertCircle,'bg-rose-100 text-rose-600')}{card('Pending',stats.pending,'Needs review',AlertCircle,'bg-blue-100 text-blue-600')}{card('Resolved',stats.resolved,'Reports closed',CheckCircle2,'bg-emerald-100 text-emerald-600')}{card('Active Reports',stats.pending,'Open reports',AlertCircle,'bg-indigo-100 text-indigo-600')}</>}{tab==='users'&&<>{card('Total Users',stats.totalUsers,'All accounts',Users,'bg-purple-100 text-purple-600')}{card('Active',stats.active,'Currently active',Users,'bg-emerald-100 text-emerald-600')}{card('Suspended',stats.suspended,'Restricted accounts',Users,'bg-rose-100 text-rose-600')}</>}{tab==='feedback'&&<>{card('Total Feedback',feedback.length,'All submissions',MessageSquare,'bg-purple-100 text-purple-600')}{card('Bugs',stats.bugs,'Bug reports',AlertCircle,'bg-rose-100 text-rose-600')}{card('Suggestions',stats.suggestions,'Suggestions',MessageSquare,'bg-amber-100 text-amber-600')}</>}{tab==='deletions'&&<>{card('Total Deletions',stats.deletions,'All requests',FileText,'bg-purple-100 text-purple-600')}{card('Pending',stats.pendingDeletions,'Needs review',AlertCircle,'bg-amber-100 text-amber-600')}{card('Completed',stats.deletions-stats.pendingDeletions,'Processed requests',CheckCircle2,'bg-emerald-100 text-emerald-600')}</>}</div>
  {error&&<div className="p-3 rounded-xl bg-rose-50 text-rose-600 text-sm">{error}</div>}<main className="rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 overflow-hidden">{loading?<p className="p-10 text-center text-slate-500">Loading dashboard...</p>:tab==='reports'?reports.map(r=><div key={r.id} className="p-4 border-b flex justify-between gap-3"><div><b>{r.reason||'Reported content'}</b><p className="text-xs text-slate-500 mt-1">Reporter: {r.reporter_id||'—'} · User: {r.reported_user_id||'—'} · {r.status||'open'}</p></div><div className="flex gap-2">{r.post_id&&<button onClick={()=>reportAction(r,'delete')} className="p-2 text-rose-600 bg-rose-50 rounded-lg"><Trash2 className="w-4 h-4"/></button>}<button onClick={()=>reportAction(r,'dismiss')} className="p-2 text-slate-600 bg-slate-100 rounded-lg"><XCircle className="w-4 h-4"/></button><button onClick={()=>reportAction(r,'resolve')} className="p-2 text-emerald-600 bg-emerald-50 rounded-lg"><CheckCircle2 className="w-4 h-4"/></button></div></div>):tab==='users'?<><div className="p-4 border-b flex gap-2"><Search className="text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search users" className="outline-none bg-transparent text-sm flex-1"/></div>{filteredUsers.map(u=><div key={u.id} className="p-4 border-b flex justify-between items-center"><div className="flex gap-3 items-center"><img src={u.avatar_url||'/auragram.png'} className="w-10 h-10 rounded-full object-cover"/><div><b>{u.full_name||u.username||'User'}</b><p className="text-xs text-slate-500">@{u.username} · {u.account_status||'active'}</p></div></div><button onClick={()=>toggleUser(u)} className="p-2 rounded-lg bg-rose-50 text-rose-600">{u.account_status==='suspended'?<Users/>:<XCircle/>}</button></div>)}</>:tab==='feedback'?feedback.map(f=><div key={f.id} className="p-4 border-b"><b>{f.type||'Suggestion'}</b><p className="mt-1 text-sm">{f.message}</p><p className="text-xs text-slate-400 mt-1">{new Date(f.created_at).toLocaleString()}</p></div>):deletions.map(d=><div key={d.user_id} className="p-4 border-b flex justify-between"><span>{d.user_id}</span><span className="text-xs text-amber-600">{d.status}</span></div>)}</main></div></div>;
}
