import React, { useState } from 'react';
import { Bug, Lightbulb, MessageCircle, Send, X } from 'lucide-react';

export default function Feedback({ onClose }) {
  const [type, setType] = useState('Suggestion');
  const [text, setText] = useState('');
  const submit = () => { if (!text.trim()) return; alert('Thanks for your feedback!'); onClose?.(); };
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/60 p-4" onClick={onClose}><div className="w-full max-w-md rounded-3xl bg-white p-6 shadow-2xl dark:bg-slate-900" onClick={e => e.stopPropagation()}><div className="flex items-start justify-between"><div><div className="mb-3 flex h-11 w-11 items-center justify-center rounded-2xl bg-violet-100 text-violet-600 dark:bg-violet-950/50"><MessageCircle /></div><h2 className="text-2xl font-black dark:text-white">Send Feedback</h2><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">Help us make Auragram better.</p></div><button onClick={onClose} className="rounded-full p-2 hover:bg-slate-100 dark:hover:bg-slate-800"><X className="h-5 w-5" /></button></div><div className="mt-5 grid grid-cols-2 gap-2">{[['Suggestion', Lightbulb], ['Bug report', Bug]].map(([label, Icon]) => <button key={label} onClick={() => setType(label)} className={`flex items-center justify-center gap-2 rounded-xl border px-3 py-2 text-xs font-bold ${type === label ? 'border-purple-500 bg-purple-50 text-purple-600 dark:bg-purple-950/40' : 'border-slate-200 text-slate-500 dark:border-slate-700'}`}><Icon className="h-4 w-4" />{label}</button>)}</div><textarea value={text} onChange={e => setText(e.target.value)} placeholder={type === 'Bug report' ? 'Describe the problem…' : 'Share your idea…'} className="mt-4 h-32 w-full resize-none rounded-xl border border-slate-200 p-3 text-sm outline-none focus:border-purple-500 dark:border-slate-700 dark:bg-slate-800 dark:text-white" /><button onClick={submit} disabled={!text.trim()} className="mt-3 flex w-full items-center justify-center gap-2 rounded-xl bg-purple-600 py-3 font-bold text-white disabled:opacity-50"><Send className="h-4 w-4" /> Submit feedback</button></div></div>;
}
