import React, { useEffect, useState } from 'react';
import { supabase } from '../supabaseClient';
import { ArrowLeft, BadgeCheck, Check, Sparkles } from 'lucide-react';

const rows = [['Profile badge','—','Blue verified badge'],['Video resolution','1080p','2K'],['Video duration','2 minutes','7 minutes'],['Bio links','2','5'],['Bio character limit','90','150'],['Caption character limit','500','1,500'],['Automated greeting messages','—','Included']];

export default function Premium({ session }) {
  const [loading, setLoading] = useState(false);
  const [subscription, setSubscription] = useState(null);
  useEffect(() => { supabase.from('profiles').select('is_verified, verified_until, created_at').eq('id', session.user.id).maybeSingle().then(({ data }) => setSubscription(data || {})); }, [session.user.id]);
  const active = subscription?.is_verified && (!subscription.verified_until || new Date(subscription.verified_until) > new Date());
  async function checkout(plan) { setLoading(true); try { const r = await fetch('/api/pay/phonepe', { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({ amount:plan==='yearly'?499:49, planType:plan, userId:session.user.id, userEmail:session.user.email }) }); const raw=await r.text(); let d={}; try { d=raw?JSON.parse(raw):{}; } catch {} if (!r.ok || !d.url) throw Error(d.error || d.message || 'PhonePe payment unavailable'); window.location.href=d.url; } catch(e) { window.alert(e.message); } finally { setLoading(false); } }
  return <main className="min-h-screen bg-gradient-to-br from-purple-50 via-white to-fuchsia-50 p-4 sm:p-8"><div className="mx-auto max-w-5xl"><button onClick={()=>window.history.back()} className="mb-6 inline-flex items-center gap-2 text-sm font-semibold text-slate-500"><ArrowLeft className="h-4 w-4"/>Back</button><section className="rounded-3xl bg-white p-6 shadow-xl sm:p-10"><div className="text-center"><Sparkles className="mx-auto h-12 w-12 rounded-2xl bg-purple-100 p-3 text-purple-600"/><h1 className="mt-4 text-3xl font-black">{active ? 'Your Premium Membership' : 'Upgrade to Premium'}</h1><p className="mt-2 text-sm text-slate-500">{active ? 'Your premium benefits are active.' : 'Unlock a verified identity and more ways to express yourself.'}</p></div>{active ? <div className="mx-auto mt-8 max-w-xl rounded-2xl border border-blue-100 bg-blue-50 p-6"><div className="flex items-center gap-2 text-lg font-bold text-blue-700"><BadgeCheck className="h-6 w-6 fill-blue-500 text-white"/>Premium active</div><div className="mt-4 grid gap-2 text-sm text-slate-700 sm:grid-cols-2"><p><b>Plan:</b> {subscription.subscription_plan === 'yearly' ? '₹499 / Year' : '₹49 / Month'}</p><p><b>Start date:</b> {subscription.created_at ? new Date(subscription.created_at).toLocaleDateString() : '—'}</p><p><b>End date:</b> {subscription.verified_until ? new Date(subscription.verified_until).toLocaleDateString() : '—'}</p></div></div> : <><div className="mt-8 overflow-hidden rounded-2xl border"><div className="grid grid-cols-3 bg-slate-50 p-4 text-sm font-bold"><span>Feature</span><span className="text-center">Free</span><span className="text-center text-purple-600">Premium</span></div>{rows.map(([a,b,c])=><div key={a} className="grid grid-cols-3 border-t p-4 text-sm"><span className="font-semibold">{a}</span><span className="text-center text-slate-500">{b}</span><span className="flex justify-center gap-1 text-center font-semibold">{c!=='—'&&<Check className="h-4 w-4 text-purple-600"/>}{c}</span></div>)}</div><div className="mt-8 grid gap-3 sm:grid-cols-2"><button disabled={loading} onClick={()=>checkout('monthly')} className="rounded-xl bg-purple-600 py-3 font-bold text-white">Get Premium · ₹49/month</button><button disabled={loading} onClick={()=>checkout('yearly')} className="rounded-xl border-2 border-purple-200 py-3 font-bold text-purple-700">Best value · ₹499/year</button></div></>}</section></div></main>;
}
