import React from 'react';
import { ArrowLeft, ShieldCheck } from 'lucide-react';

const sections = [
  ['Who we are', 'Auragram is operated by Sarvesh Kumar. In this policy, “Auragram”, “we”, “us” and “our” mean the Auragram social SaaS platform and its operator.'],
  ['Information we collect', 'We collect account and profile information such as your email address, username, display name, avatar and bio. We process content you choose to upload or send, including posts, photos, videos, comments, messages and support requests. We also receive usage and technical information such as device/browser details, approximate activity timestamps, crash logs and interactions needed to operate, secure and improve the service.'],
  ['How we use information', 'We use information to authenticate accounts, provide feeds and profiles, deliver messaging and notifications, enforce Free and Premium feature limits, process support requests, prevent abuse, maintain security, measure product performance and communicate service updates.'],
  ['Storage and service providers', 'Auragram uses Supabase Authentication, database services and storage to operate accounts and user content. We may use infrastructure, analytics, email, customer-support and payment providers as service processors. Providers receive only the information needed for their contracted function and are expected to protect it.'],
  ['Premium payments', 'Premium subscriptions may be processed through RBI-regulated or otherwise authorised payment gateways, including the provider shown at checkout. Auragram does not store raw card numbers, CVV, UPI PINs or banking passwords on its servers. Payment providers process payment credentials under their own policies; Auragram receives transaction and subscription status needed to provide Premium benefits and support.'],
  ['Cookies and similar technologies', 'We use essential local storage, cookies or similar technologies for authentication, preferences, session continuity, security and basic usage measurement. You can control cookies through your browser, but disabling essential technologies may affect sign-in or core features.'],
  ['Security and retention', 'We use HTTPS, access controls, row-level database policies and operational safeguards designed to protect information. No online service can guarantee absolute security. We retain information for as long as needed to provide the service, meet legal obligations, resolve disputes, enforce agreements and maintain legitimate business records, then delete or anonymise it where reasonably possible.'],
  ['Your choices and rights', 'Subject to applicable law, you may access, correct or delete profile information, manage content through the app, request account deletion, withdraw optional permissions and ask about processing of your data. Contact us to make a privacy request; we may verify your identity before acting. You may also complain to your local data-protection authority.'],
  ['Children and third-party links', 'Auragram is not directed to children who cannot legally use the service. Do not create an account if you are not permitted to do so. Links to third-party websites or services are governed by their own terms and privacy notices.'],
  ['Contact and updates', 'For privacy questions or data requests, email support@auragram.in. We may update this policy as Auragram changes. The “Last updated” date shows when the current version was published.']
];

export default function Privacy({ onBack }) {
  return <div className="min-h-screen bg-slate-50 p-4 text-slate-900 dark:bg-slate-950 dark:text-white md:p-8"><div className="mx-auto max-w-3xl"><button onClick={onBack} className="mb-6 inline-flex items-center gap-2 rounded-xl px-3 py-2 text-sm font-bold text-purple-600 hover:bg-purple-50 dark:hover:bg-slate-800"><ArrowLeft className="h-4 w-4" /> Back</button><div className="rounded-3xl bg-white p-6 shadow-sm dark:bg-slate-900 md:p-10"><div className="mb-8 flex items-center gap-4"><div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-purple-100 text-purple-600 dark:bg-purple-950/50"><ShieldCheck className="h-7 w-7" /></div><div><h1 className="text-3xl font-black">Privacy Policy</h1><p className="text-sm text-slate-500 dark:text-slate-400">Last updated: 2 October 2026</p></div></div>{sections.map(([title, body]) => <section key={title} className="border-t border-slate-100 py-5 dark:border-slate-800"><h2 className="text-lg font-bold">{title}</h2><p className="mt-2 text-sm leading-7 text-slate-600 dark:text-slate-300">{body}</p></section>)}</div></div></div>;
}
