import React, { useState } from 'react';
import { ArrowLeft, FileText } from 'lucide-react';

const sections = [
  ['Acceptance and operator', 'These Terms and Conditions govern your use of Auragram, a social SaaS platform operated by Sarvesh Kumar. By creating an account or using Auragram, you agree to these Terms and our Privacy Policy.'],
  ['Eligibility and account responsibility', 'You must be legally permitted to use the service and provide accurate, current account information. Keep your password and sign-in methods confidential, promptly report unauthorised access, and do not use another person\'s account. You are responsible for activity performed through your account.'],
  ['Free and Premium features', 'Free accounts may upload videos up to 2 minutes and 1080p, use up to 2 bio links, a 90-character bio and 500-character captions, with standard support. Premium accounts may receive a verified profile badge, videos up to 7 minutes and 2K, up to 5 bio links, a 150-character bio, 1,500-character captions and priority support. Limits and benefits are subject to the plan shown at checkout and may change prospectively.'],
  ['Fair use and uploads', 'Upload or share only material you own or are authorised to use. Do not upload unlawful, fraudulent, abusive, hateful, sexually exploitative, threatening, defamatory, infringing or malicious content; scrape the service; impersonate others; spam users; or bypass technical, storage or plan limits. We may review, restrict or remove content that violates these Terms or creates risk.'],
  ['Payments and subscriptions', 'Premium pricing, billing period and taxes are shown before checkout. Payments are handled by the third-party gateway presented in the app; Auragram does not store raw card numbers, CVV, UPI PINs or banking passwords. Refunds, cancellations and eligibility are governed by the separate Refund & Cancellation Policy.'],
  ['Your content and our licence', 'You retain ownership of content you submit. You grant Auragram a limited, non-exclusive, worldwide licence to host, store, reproduce, format, display and transmit that content only as needed to operate, secure and improve the service and provide it to your selected audience.'],
  ['Auragram intellectual property', 'Auragram names, logos, interface, software, design and original materials belong to Sarvesh Kumar or our licensors. Except for the rights expressly granted in these Terms, you may not copy, modify, distribute, reverse engineer or commercially exploit them.'],
  ['Moderation, suspension and termination', 'We may suspend, limit or terminate accounts or remove content for violations, fraud, security concerns, legal requests or prolonged inactivity. You may stop using the service or request account deletion. Clauses concerning ownership, payment obligations, liability and disputes survive termination where applicable.'],
  ['Availability and liability', 'Auragram is provided on an as-available basis. We work to keep the service reliable but do not promise uninterrupted access, error-free operation or permanent availability of any feature. To the extent permitted by law, Sarvesh Kumar is not liable for indirect or consequential loss arising from use of the service.'],
  ['Changes and contact', 'We may update these Terms when the service or law changes. Material updates will be communicated through the app or website where reasonably possible. Continued use after the effective date means you accept the updated Terms. Questions can be sent to support@auragram.in.']
];

export default function Terms({ onBack }) {
  const [hindi, setHindi] = useState(false);
  return <div className="min-h-screen bg-slate-50 p-4 text-slate-900 dark:bg-slate-950 dark:text-white md:p-8"><div className="mx-auto max-w-3xl"><button onClick={onBack} className="mb-6 inline-flex items-center gap-2 rounded-xl px-3 py-2 text-sm font-bold text-purple-600 hover:bg-purple-50 dark:hover:bg-slate-800"><ArrowLeft className="h-4 w-4" /> Back</button><div className="rounded-3xl bg-white p-6 shadow-sm dark:bg-slate-900 md:p-10"><div className="mb-8 flex items-start justify-between gap-4"><div className="flex items-center gap-4"><div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-purple-100 text-purple-600 dark:bg-purple-950/50"><FileText className="h-7 w-7" /></div><div><h1 className="text-3xl font-black">{hindi ? 'नियम और शर्तें' : 'Terms & Conditions'}</h1><p className="text-sm text-slate-500 dark:text-slate-400">Last updated: 2 October 2026</p></div></div><div className="flex shrink-0 gap-1 rounded-xl bg-slate-100 p-1 text-xs font-bold dark:bg-slate-800"><button onClick={() => setHindi(false)} className={!hindi ? 'rounded-lg bg-white px-2 py-1 text-purple-600 shadow-sm dark:bg-slate-700' : 'px-2 py-1 text-slate-500'}>English</button><button onClick={() => setHindi(true)} className={hindi ? 'rounded-lg bg-white px-2 py-1 text-purple-600 shadow-sm dark:bg-slate-700' : 'px-2 py-1 text-slate-500'}>हिन्दी</button></div></div>{hindi ? <div className="space-y-5 text-sm leading-7 text-slate-600 dark:text-slate-300"><p><b>स्वीकृति:</b> Auragram का उपयोग करने पर आप इन नियमों और Privacy Policy से सहमत होते हैं।</p><p>खाते की जानकारी सही रखें और password सुरक्षित रखें। किसी अन्य व्यक्ति की identity का गलत उपयोग, spam, illegal या harmful content, scraping और feature limits bypass करना मना है।</p><p>Free plan में 2 मिनट/1080p video, 2 bio links और निर्धारित character limits हैं। Premium plan में verified badge, 7 मिनट/2K video, 5 links और priority support मिलते हैं।</p><p>आप अपने content के मालिक रहते हैं, लेकिन service चलाने के लिए Auragram को सीमित उपयोग की अनुमति देते हैं। नियम तोड़ने पर account suspend या terminate किया जा सकता है।</p><p>Payment और refund के नियम अलग Refund &amp; Cancellation Policy में दिए गए हैं। सवालों के लिए support@auragram.in पर संपर्क करें।</p></div> : sections.map(([title, body]) => <section key={title} className="border-t border-slate-100 py-5 dark:border-slate-800"><h2 className="text-lg font-bold">{title}</h2><p className="mt-2 text-sm leading-7 text-slate-600 dark:text-slate-300">{body}</p></section>)}</div></div></div>;
}
